(function() {

  window._memberships = [{
    PersonId: 10192837,
    From: '2015-09-01',
    To: '2016-08-31',
    Name: 'Registered member',
    FirstName: 'Emilia',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/emilia.jpg',
    OrganizationId: 501,
    OrganizationLogoUrl: 'img/skate-canada.png',
    OrganizationName: "Skate Canada",
    OrganizationAddress: "261 – 1200 St. Laurent Blvd., Ottawa, ON, K1K 3B8",
    OrganizationPhone: "(613) 747-1007",
    OrganizationEmail: "info@skatecanada.ca",
    OrganizationWebsite: "skatecanada.ca"
  }, {
    PersonId: 17632745,
    From: '2016-01-01',
    To: '2016-12-31',
    Name: 'ADULTE Membre 2016 /JEANNE-MANCE (résident)',
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 101,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal",
    OrganizationAddress: "285, rue Gary-Carter, bur. 202, Montréal, QC, H2R 2W1, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@tennismontreal.qc.ca",
    OrganizationWebsite: "www.tennismontreal.qc.ca"
  }, {
    PersonId: 10192837,
    From: '2016-01-01',
    To: '2016-12-31',
    Name: 'Accès au gymnase',
    FirstName: 'Emilia',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/emilia.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal",
    OrganizationAddress: "1000 Ave Émile-Journault, Montréal, QC, H2M 2E7, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@sportsmontreal.com",
    OrganizationWebsite: "www.sportsmontreal.com"
  }, {
    PersonId: 20938472,
    From: '2016-01-01',
    To: '2016-12-31',
    Name: 'Accès au gymnase',
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal",
    OrganizationAddress: "1000 Ave Émile-Journault, Montréal, QC, H2M 2E7, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@sportsmontreal.com",
    OrganizationWebsite: "www.sportsmontreal.com"
  }, {
    PersonId: 30293847,
    From: '2016-01-01',
    To: '2016-12-31',
    Name: 'JUNIOR Membre 2016 Claude-Robillard (résident)',
    FirstName: 'Eloi',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/eloi.jpg',
    OrganizationId: 101,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal",
    OrganizationAddress: "285, rue Gary-Carter, bur. 202, Montréal, QC, H2R 2W1, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@tennismontreal.qc.ca",
    OrganizationWebsite: "www.tennismontreal.qc.ca"
  }];

  window._purchases = [{
    Id: 1000,
    Name: 'Camp option hockey cosom - Hockey cosom, 7-8 ans - Semaine 7 : 8 au 12 août 2016',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 20938472,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1001,
    Name: "Activités de postures et d'étirements - Power yoga - Printemps 2016",
    Type: 'Activity',
    InvoiceId: 2001,
    PersonId: 10192837,
    FirstName: 'Emilia',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/emilia.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1002,
    Name: "Camp multisport - Club des Champions (7-8 ans) - Semaine 2 : 4 au 8 juillet 2016",
    Type: 'Activity',
    InvoiceId: 2002,
    PersonId: 30293847,
    FirstName: 'Eloi',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/eloi.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1003,
    Name: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00 - Du 21 mai au 3 sept. Les mardis de 19:00 à 21:00, du 21 mai 2016 jusqu'au 3 septembre 2016.",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 30293847,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1004,
    Name: "Carte de membre 2016 adulte (résident) Tennis  Montréal/Jeanne-Mance",
    Type: 'Membership',
    InvoiceId: 2004,
    PersonId: 17632745,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1005,
    Name: "Carte de membre 2016 adulte (résident) Tennis  Montréal/Jeanne-Mance",
    Type: 'Membership',
    InvoiceId: 2005,
    PersonId: 30293847,
    FirstName: 'Eloi',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/eloi.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }];

  window._events = [{
    Id: 1000,
    When: '2016-08-08 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'lundi 8 août',
    Name: 'Camp option hockey cosom',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 20938472,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1001,
    When: '2016-08-09 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'mardi 9 août',
    Name: 'Camp option hockey cosom',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 20938472,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1002,
    When: '2016-08-09 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'mardi 9 août',
    Name: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 30293847,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1003,
    When: '2016-08-10 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'mercredi 10 août',
    Name: 'Camp option hockey cosom',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 20938472,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1004,
    When: '2016-08-11 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'jeudi 11 août',
    Name: 'Camp option hockey cosom',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 20938472,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1005,
    When: '2016-08-12 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'vendredi 12 août',
    Name: 'Camp option hockey cosom',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 20938472,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1006,
    When: '2016-08-16 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'mardi 16 août',
    Name: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 30293847,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1007,
    When: '2016-08-23 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'mardi 23 août',
    Name: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 30293847,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1008,
    When: '2016-08-30 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'mardi 30 août',
    Name: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 30293847,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }];

  window._communications = [{
    Id: 1000,
    Status: 'Unread',
    When: '2016-08-06',
    From: 'Seb Goal',
    Subject: "Camp option hockey cosom",
    Body: "Bonjour Ludovic,<br/>Voici la liste des choses à apporter:<br/><ul><li>bouteille d'eau</li><li>bâton</li><li>protèges tibias</li></ul>",
    InvoiceId: 2003,
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1001,
    Status: 'Read',
    When: '2016-08-01',
    From: 'Julie Yoga',
    Subject: "Power yoga - mercredi 20 mai, cours annulé",
    Body: "Le cours de ce soir a été annulé. Il sera repris à la fin de la session.",
    InvoiceId: 2003,
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1002,
    Status: 'Read',
    When: '2016-06-30',
    From: 'Rafa Nadal',
    Subject: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00",
    Body: "Bienvenu au cours que je vais donner. J'ai pris ma retraite professionnelle justement pour vous!",
    InvoiceId: 2003,
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }];

}.call(this));